<?php

return [
    'name' => 'Inventory',

    'classification' => [
        'version' => 'asset-classifier-v1',
        'queue' => env('SENTINEL_QUEUE_ASSET_CLASSIFICATION', 'inventory-asset-classification'),
        'interval_hours' => (int) env('SENTINEL_ASSET_CLASSIFICATION_INTERVAL', 24),
        'http_probe_enabled' => true,

        'asset_types' => [
            'website',
            'web_application',
            'rest_api',
            'soap_api',
            'graphql',
            'mail_server',
            'database',
            'vpn',
            'authentication',
            'dns',
            'devops',
            'monitoring',
            'storage',
            'infrastructure',
            'unknown',
        ],

        'asset_roles' => [
            'centro_universitario',
            'institucional',
            'biblioteca',
            'sistema_escolar',
            'siiau',
            'lms',
            'correo_institucional',
            'investigacion',
            'editorial',
            'cultura',
            'recursos_humanos',
            'finanzas',
            'integracion',
            'infraestructura',
            'desarrollo',
            'qa',
            'testing',
            'sandbox',
            'blockchain',
            'seguridad',
            'control_de_versiones',
            'unknown',
        ],
    ],
];
